### ISSUE TITLE
feat: use specific vercel-version 

### ISSUE THREAD

**Issue by amondnet** [amondnet/vercel-action#168]

**Comment by anasmebarki1996-c4t** [comment]
yeah we have this issue for the Vercel CLI 27 version

**Comment by mgtitimoli** [comment]
Vercel Yesterday released a new version ([27.0.2](https://github.com/vercel/vercel/releases/tag/vercel%4027.0.2)) that fixes this issue.

The problem is that the cli is executed using [npx](https://docs.npmjs.com/cli/v7/commands/npx) and this one has a cache, meaning that in the same project, if at least one PR used the version with the bug (`27.0.1`), all the others PRs are gonna used this same version.

The default node setup configured for ubuntu-latest deviates a bit from a standard configuration as the npx cache is not located where it should be (`$(npm config get cache)/_npx`), so is not so easy to clear it (I haven't been able to do this).

The good thing is that there is action for setup node that doesn't have cache by default: [actions/setup-node](https://github.com/actions/setup-node), so if instead of relying in the one that comes in the container, we configure a new node version using this action that has no cache by default, `npx` will download the latest vercel cli that has no error.

This snippet configures [actions/setup-node](https://github.com/actions/setup-node) to use the latest lts node version:

```yml
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
```

**Comment by anasmebarki1996-c4t** [comment]
@mgtitimoli thanks it works for me but it doesn't work with node-version 14

**Comment by BossBele** [comment]
@anasmebarki1996-c4t  What node version does it work with?

**Comment by BossBele** [comment]
+1 to this. Being able to specify CLI version. would be great

**Comment by anasmebarki1996-c4t** [comment]
@BossBele now it works with    node-version: lts/* => 16v
